INSERT INTO "TB_USER_ROLE"
  ("USER_ID","ROLE_ID")
VALUES(1.00,1.00);

INSERT INTO "TB_USER_ROLE"
  ("USER_ID","ROLE_ID")
VALUES(1.00,2.00);

INSERT INTO "TB_USER_ROLE"
  ("USER_ID","ROLE_ID")
VALUES(2.00,2.00);

