package com.anders.pomelo.databus.dao.bo;

public class ColumnsWithBLOBs extends Columns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    private String columnDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_TYPE
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    private String columnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.GENERATION_EXPRESSION
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    private String generationExpression;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_DEFAULT
     *
     * @return the value of COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public String getColumnDefault() {
        return columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_DEFAULT
     *
     * @param columnDefault the value for COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public void setColumnDefault(String columnDefault) {
        this.columnDefault = columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_TYPE
     *
     * @return the value of COLUMNS.COLUMN_TYPE
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_TYPE
     *
     * @param columnType the value for COLUMNS.COLUMN_TYPE
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.GENERATION_EXPRESSION
     *
     * @return the value of COLUMNS.GENERATION_EXPRESSION
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public String getGenerationExpression() {
        return generationExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.GENERATION_EXPRESSION
     *
     * @param generationExpression the value for COLUMNS.GENERATION_EXPRESSION
     *
     * @mbg.generated Tue Jul 25 11:27:10 CST 2017
     */
    public void setGenerationExpression(String generationExpression) {
        this.generationExpression = generationExpression;
    }
}