package com.baidu.rigel.unique.bo.pangu;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustContactPhoneBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户资料ID")
	private Long custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.contact_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "联系人ID")
	private Long contactId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.phone_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "电话类型:0,座机;1,手机")
	private Byte phoneType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.country_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "国家代码")
	private String countryNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.area_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "区号")
	private String areaNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.phone_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "座机号码或手机号")
	private String phoneNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.ext_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "分机号")
	private String extNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.full_phone
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "全部号码")
	private String fullPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "增加人")
	private Long addUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "增加时间")
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "是否失效:0,否;1:失效")
	private Byte disabledFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "失效原因")
	private String disabledReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "失效时间")
	private Date disabledTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.last_call_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "鏈?悗涓??閫氳瘽鏃堕棿")
	private Date lastCallTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.call_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "鎬婚?璇濇?鏁")
	private Integer callNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact_phone.call_num_day
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "褰撳ぉ閫氳瘽娆℃暟")
	private Integer callNumDay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.id
	 * 
	 * @return the value of cust_contact_phone.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.id
	 * 
	 * @param id
	 *            the value for cust_contact_phone.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.cust_id
	 * 
	 * @return the value of cust_contact_phone.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.cust_id
	 * 
	 * @param custId
	 *            the value for cust_contact_phone.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCustId(Long custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.contact_id
	 * 
	 * @return the value of cust_contact_phone.contact_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getContactId() {
		return contactId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.contact_id
	 * 
	 * @param contactId
	 *            the value for cust_contact_phone.contact_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setContactId(Long contactId) {
		setField("contactId", contactId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.phone_type
	 * 
	 * @return the value of cust_contact_phone.phone_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getPhoneType() {
		return phoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.phone_type
	 * 
	 * @param phoneType
	 *            the value for cust_contact_phone.phone_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPhoneType(Byte phoneType) {
		setField("phoneType", phoneType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.country_num
	 * 
	 * @return the value of cust_contact_phone.country_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getCountryNum() {
		return countryNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.country_num
	 * 
	 * @param countryNum
	 *            the value for cust_contact_phone.country_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCountryNum(String countryNum) {
		countryNum = countryNum == null ? null : countryNum.trim();

		setField("countryNum", countryNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.area_num
	 * 
	 * @return the value of cust_contact_phone.area_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getAreaNum() {
		return areaNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.area_num
	 * 
	 * @param areaNum
	 *            the value for cust_contact_phone.area_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAreaNum(String areaNum) {
		areaNum = areaNum == null ? null : areaNum.trim();

		setField("areaNum", areaNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.phone_num
	 * 
	 * @return the value of cust_contact_phone.phone_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.phone_num
	 * 
	 * @param phoneNum
	 *            the value for cust_contact_phone.phone_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPhoneNum(String phoneNum) {
		phoneNum = phoneNum == null ? null : phoneNum.trim();

		setField("phoneNum", phoneNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.ext_num
	 * 
	 * @return the value of cust_contact_phone.ext_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getExtNum() {
		return extNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.ext_num
	 * 
	 * @param extNum
	 *            the value for cust_contact_phone.ext_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setExtNum(String extNum) {
		extNum = extNum == null ? null : extNum.trim();

		setField("extNum", extNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.full_phone
	 * 
	 * @return the value of cust_contact_phone.full_phone
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getFullPhone() {
		return fullPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.full_phone
	 * 
	 * @param fullPhone
	 *            the value for cust_contact_phone.full_phone
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setFullPhone(String fullPhone) {
		fullPhone = fullPhone == null ? null : fullPhone.trim();

		setField("fullPhone", fullPhone);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.add_ucid
	 * 
	 * @return the value of cust_contact_phone.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getAddUcid() {
		return addUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.add_ucid
	 * 
	 * @param addUcid
	 *            the value for cust_contact_phone.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddUcid(Long addUcid) {
		setField("addUcid", addUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.add_time
	 * 
	 * @return the value of cust_contact_phone.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.add_time
	 * 
	 * @param addTime
	 *            the value for cust_contact_phone.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddTime(Date addTime) {
		setField("addTime", addTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.disabled_flag
	 * 
	 * @return the value of cust_contact_phone.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getDisabledFlag() {
		return disabledFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.disabled_flag
	 * 
	 * @param disabledFlag
	 *            the value for cust_contact_phone.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledFlag(Byte disabledFlag) {
		setField("disabledFlag", disabledFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.disabled_reason
	 * 
	 * @return the value of cust_contact_phone.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getDisabledReason() {
		return disabledReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.disabled_reason
	 * 
	 * @param disabledReason
	 *            the value for cust_contact_phone.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledReason(String disabledReason) {
		disabledReason = disabledReason == null ? null : disabledReason.trim();

		setField("disabledReason", disabledReason);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.disabled_time
	 * 
	 * @return the value of cust_contact_phone.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getDisabledTime() {
		return disabledTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.disabled_time
	 * 
	 * @param disabledTime
	 *            the value for cust_contact_phone.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledTime(Date disabledTime) {
		setField("disabledTime", disabledTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.last_call_time
	 * 
	 * @return the value of cust_contact_phone.last_call_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getLastCallTime() {
		return lastCallTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.last_call_time
	 * 
	 * @param lastCallTime
	 *            the value for cust_contact_phone.last_call_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setLastCallTime(Date lastCallTime) {
		setField("lastCallTime", lastCallTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.call_num
	 * 
	 * @return the value of cust_contact_phone.call_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getCallNum() {
		return callNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.call_num
	 * 
	 * @param callNum
	 *            the value for cust_contact_phone.call_num
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCallNum(Integer callNum) {
		setField("callNum", callNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact_phone.call_num_day
	 * 
	 * @return the value of cust_contact_phone.call_num_day
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getCallNumDay() {
		return callNumDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact_phone.call_num_day
	 * 
	 * @param callNumDay
	 *            the value for cust_contact_phone.call_num_day
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCallNumDay(Integer callNumDay) {
		setField("callNumDay", callNumDay);
	}
}