package com.baidu.rigel.unique.bo.pangu;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustDistributeBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_distribute.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_distribute.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户资料id")
	private Integer custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_distribute.state
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "当为1时,代表最近一下时间")
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_distribute.distribute_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "下发时间")
	private Date distributeTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_distribute.id
	 * 
	 * @return the value of cust_distribute.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_distribute.id
	 * 
	 * @param id
	 *            the value for cust_distribute.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setId(Integer id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_distribute.cust_id
	 * 
	 * @return the value of cust_distribute.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_distribute.cust_id
	 * 
	 * @param custId
	 *            the value for cust_distribute.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCustId(Integer custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_distribute.state
	 * 
	 * @return the value of cust_distribute.state
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_distribute.state
	 * 
	 * @param state
	 *            the value for cust_distribute.state
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setState(Byte state) {
		setField("state", state);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_distribute.distribute_time
	 * 
	 * @return the value of cust_distribute.distribute_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getDistributeTime() {
		return distributeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_distribute.distribute_time
	 * 
	 * @param distributeTime
	 *            the value for cust_distribute.distribute_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDistributeTime(Date distributeTime) {
		setField("distributeTime", distributeTime);
	}
}