package com.baidu.rigel.unique.bo.pangu;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustContactBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户资料ID")
	private Integer custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "名称")
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.company_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "公司邮箱")
	private String companyMail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.personal_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "私人邮箱")
	private String personalMail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.duty
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "职务")
	private String duty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.policy_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "决策类型")
	private Integer policyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.gender
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "性别:0,男;1,女")
	private Byte gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "备注")
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "增加人")
	private Integer addUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "增加时间")
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "是否失效:0,否;1,失效")
	private Short disabledFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "失效原因")
	private String disabledReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust_contact.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "失效时间")
	private Date disabledTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.id
	 * 
	 * @return the value of cust_contact.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.id
	 * 
	 * @param id
	 *            the value for cust_contact.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setId(Integer id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.cust_id
	 * 
	 * @return the value of cust_contact.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.cust_id
	 * 
	 * @param custId
	 *            the value for cust_contact.cust_id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCustId(Integer custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.name
	 * 
	 * @return the value of cust_contact.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.name
	 * 
	 * @param name
	 *            the value for cust_contact.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setName(String name) {
		name = name == null ? null : name.trim();

		setField("name", name);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.company_mail
	 * 
	 * @return the value of cust_contact.company_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getCompanyMail() {
		return companyMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.company_mail
	 * 
	 * @param companyMail
	 *            the value for cust_contact.company_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setCompanyMail(String companyMail) {
		companyMail = companyMail == null ? null : companyMail.trim();

		setField("companyMail", companyMail);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.personal_mail
	 * 
	 * @return the value of cust_contact.personal_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getPersonalMail() {
		return personalMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.personal_mail
	 * 
	 * @param personalMail
	 *            the value for cust_contact.personal_mail
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPersonalMail(String personalMail) {
		personalMail = personalMail == null ? null : personalMail.trim();

		setField("personalMail", personalMail);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.duty
	 * 
	 * @return the value of cust_contact.duty
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getDuty() {
		return duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.duty
	 * 
	 * @param duty
	 *            the value for cust_contact.duty
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDuty(String duty) {
		duty = duty == null ? null : duty.trim();

		setField("duty", duty);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.policy_type
	 * 
	 * @return the value of cust_contact.policy_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getPolicyType() {
		return policyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.policy_type
	 * 
	 * @param policyType
	 *            the value for cust_contact.policy_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPolicyType(Integer policyType) {
		setField("policyType", policyType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.gender
	 * 
	 * @return the value of cust_contact.gender
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.gender
	 * 
	 * @param gender
	 *            the value for cust_contact.gender
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setGender(Byte gender) {
		setField("gender", gender);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.remark
	 * 
	 * @return the value of cust_contact.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.remark
	 * 
	 * @param remark
	 *            the value for cust_contact.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setRemark(String remark) {
		remark = remark == null ? null : remark.trim();

		setField("remark", remark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.add_ucid
	 * 
	 * @return the value of cust_contact.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getAddUcid() {
		return addUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.add_ucid
	 * 
	 * @param addUcid
	 *            the value for cust_contact.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddUcid(Integer addUcid) {
		setField("addUcid", addUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.add_time
	 * 
	 * @return the value of cust_contact.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.add_time
	 * 
	 * @param addTime
	 *            the value for cust_contact.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddTime(Date addTime) {
		setField("addTime", addTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.disabled_flag
	 * 
	 * @return the value of cust_contact.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Short getDisabledFlag() {
		return disabledFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.disabled_flag
	 * 
	 * @param disabledFlag
	 *            the value for cust_contact.disabled_flag
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledFlag(Short disabledFlag) {
		setField("disabledFlag", disabledFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.disabled_reason
	 * 
	 * @return the value of cust_contact.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getDisabledReason() {
		return disabledReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.disabled_reason
	 * 
	 * @param disabledReason
	 *            the value for cust_contact.disabled_reason
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledReason(String disabledReason) {
		disabledReason = disabledReason == null ? null : disabledReason.trim();

		setField("disabledReason", disabledReason);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust_contact.disabled_time
	 * 
	 * @return the value of cust_contact.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getDisabledTime() {
		return disabledTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust_contact.disabled_time
	 * 
	 * @param disabledTime
	 *            the value for cust_contact.disabled_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setDisabledTime(Date disabledTime) {
		setField("disabledTime", disabledTime);
	}
}