package com.baidu.rigel.unique.bo.pangu;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户类型 0:普通企业 1:特殊企业 2:个人客户 3:广告代理")
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户名称")
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.branch
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户分支机构名称")
	private String branch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.full_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户全称")
	private String fullName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.posid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "所属运营单位")
	private Integer posid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.trade
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "客户行业")
	private Integer trade;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.per_remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "个人备注")
	private String perRemark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "备注")
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "网站类型")
	private Byte siteType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.no_site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "暂无网站说明")
	private Byte noSiteType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.site_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "网站名称")
	private String siteName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.site_url
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "网站URL")
	private String siteUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.site_domain
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "网站URL主域")
	private String siteDomain;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.source
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "录入方式:0,销售录入;1,批量导入;2,网上申请;3,来电咨询;4,来电留言;5,IM沟通;6,www2注册;7,其他来源;8,线索转化")
	private Byte source;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.pri
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "优先级别:0,优先审核;1,入自有库;2,入公共库")
	private Byte pri;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.stat_1
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "一级状态")
	private String stat1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.stat_2
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "二级状态")
	private String stat2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.in_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "IN跟进人")
	private Long inUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.out_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "OUT跟进人")
	private Integer outUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "录入人")
	private Integer addUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "录入时间")
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.upd_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "修改人")
	private Integer updUcid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.upd_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "修改时间")
	private Date updTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.auto_audit_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "自动审核结果:0,通过;1,质疑;2,老户新开;3,一户多开;4,重复;5,下一步继续审核;6,季节性备案;7,CSC下发疑似重复;8,公司名质疑")
	private Byte autoAuditType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.version
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "乐观锁版本号")
	private Integer version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.business_no
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "当前商机数")
	private Byte businessNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.business_details
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "6要素")
	private String businessDetails;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cust.stat_3
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	@ColumnDescription(desc = "三级状态")
	private String stat3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.id
	 * 
	 * @return the value of cust.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.id
	 * 
	 * @param id
	 *            the value for cust.id
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.type
	 * 
	 * @return the value of cust.type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.type
	 * 
	 * @param type
	 *            the value for cust.type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setType(Byte type) {
		setField("type", type);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.name
	 * 
	 * @return the value of cust.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.name
	 * 
	 * @param name
	 *            the value for cust.name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setName(String name) {
		name = name == null ? null : name.trim();

		setField("name", name);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.branch
	 * 
	 * @return the value of cust.branch
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getBranch() {
		return branch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.branch
	 * 
	 * @param branch
	 *            the value for cust.branch
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setBranch(String branch) {
		branch = branch == null ? null : branch.trim();

		setField("branch", branch);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.full_name
	 * 
	 * @return the value of cust.full_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getFullName() {
		return fullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.full_name
	 * 
	 * @param fullName
	 *            the value for cust.full_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setFullName(String fullName) {
		fullName = fullName == null ? null : fullName.trim();

		setField("fullName", fullName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.posid
	 * 
	 * @return the value of cust.posid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getPosid() {
		return posid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.posid
	 * 
	 * @param posid
	 *            the value for cust.posid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPosid(Integer posid) {
		setField("posid", posid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.trade
	 * 
	 * @return the value of cust.trade
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getTrade() {
		return trade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.trade
	 * 
	 * @param trade
	 *            the value for cust.trade
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setTrade(Integer trade) {
		setField("trade", trade);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.per_remark
	 * 
	 * @return the value of cust.per_remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getPerRemark() {
		return perRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.per_remark
	 * 
	 * @param perRemark
	 *            the value for cust.per_remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPerRemark(String perRemark) {
		perRemark = perRemark == null ? null : perRemark.trim();

		setField("perRemark", perRemark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.remark
	 * 
	 * @return the value of cust.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.remark
	 * 
	 * @param remark
	 *            the value for cust.remark
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setRemark(String remark) {
		remark = remark == null ? null : remark.trim();

		setField("remark", remark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.site_type
	 * 
	 * @return the value of cust.site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getSiteType() {
		return siteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.site_type
	 * 
	 * @param siteType
	 *            the value for cust.site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setSiteType(Byte siteType) {
		setField("siteType", siteType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.no_site_type
	 * 
	 * @return the value of cust.no_site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getNoSiteType() {
		return noSiteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.no_site_type
	 * 
	 * @param noSiteType
	 *            the value for cust.no_site_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setNoSiteType(Byte noSiteType) {
		setField("noSiteType", noSiteType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.site_name
	 * 
	 * @return the value of cust.site_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.site_name
	 * 
	 * @param siteName
	 *            the value for cust.site_name
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setSiteName(String siteName) {
		siteName = siteName == null ? null : siteName.trim();

		setField("siteName", siteName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.site_url
	 * 
	 * @return the value of cust.site_url
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getSiteUrl() {
		return siteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.site_url
	 * 
	 * @param siteUrl
	 *            the value for cust.site_url
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setSiteUrl(String siteUrl) {
		siteUrl = siteUrl == null ? null : siteUrl.trim();

		setField("siteUrl", siteUrl);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.site_domain
	 * 
	 * @return the value of cust.site_domain
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getSiteDomain() {
		return siteDomain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.site_domain
	 * 
	 * @param siteDomain
	 *            the value for cust.site_domain
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setSiteDomain(String siteDomain) {
		siteDomain = siteDomain == null ? null : siteDomain.trim();

		setField("siteDomain", siteDomain);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.source
	 * 
	 * @return the value of cust.source
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.source
	 * 
	 * @param source
	 *            the value for cust.source
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setSource(Byte source) {
		setField("source", source);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.pri
	 * 
	 * @return the value of cust.pri
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getPri() {
		return pri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.pri
	 * 
	 * @param pri
	 *            the value for cust.pri
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setPri(Byte pri) {
		setField("pri", pri);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.stat_1
	 * 
	 * @return the value of cust.stat_1
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getStat1() {
		return stat1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.stat_1
	 * 
	 * @param stat1
	 *            the value for cust.stat_1
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setStat1(String stat1) {
		stat1 = stat1 == null ? null : stat1.trim();

		setField("stat1", stat1);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.stat_2
	 * 
	 * @return the value of cust.stat_2
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getStat2() {
		return stat2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.stat_2
	 * 
	 * @param stat2
	 *            the value for cust.stat_2
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setStat2(String stat2) {
		stat2 = stat2 == null ? null : stat2.trim();

		setField("stat2", stat2);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.in_ucid
	 * 
	 * @return the value of cust.in_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Long getInUcid() {
		return inUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.in_ucid
	 * 
	 * @param inUcid
	 *            the value for cust.in_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setInUcid(Long inUcid) {
		setField("inUcid", inUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.out_ucid
	 * 
	 * @return the value of cust.out_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getOutUcid() {
		return outUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.out_ucid
	 * 
	 * @param outUcid
	 *            the value for cust.out_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setOutUcid(Integer outUcid) {
		setField("outUcid", outUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.add_ucid
	 * 
	 * @return the value of cust.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getAddUcid() {
		return addUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.add_ucid
	 * 
	 * @param addUcid
	 *            the value for cust.add_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddUcid(Integer addUcid) {
		setField("addUcid", addUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.add_time
	 * 
	 * @return the value of cust.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.add_time
	 * 
	 * @param addTime
	 *            the value for cust.add_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAddTime(Date addTime) {
		setField("addTime", addTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.upd_ucid
	 * 
	 * @return the value of cust.upd_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getUpdUcid() {
		return updUcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.upd_ucid
	 * 
	 * @param updUcid
	 *            the value for cust.upd_ucid
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setUpdUcid(Integer updUcid) {
		setField("updUcid", updUcid);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.upd_time
	 * 
	 * @return the value of cust.upd_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Date getUpdTime() {
		return updTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.upd_time
	 * 
	 * @param updTime
	 *            the value for cust.upd_time
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setUpdTime(Date updTime) {
		setField("updTime", updTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.auto_audit_type
	 * 
	 * @return the value of cust.auto_audit_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getAutoAuditType() {
		return autoAuditType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.auto_audit_type
	 * 
	 * @param autoAuditType
	 *            the value for cust.auto_audit_type
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setAutoAuditType(Byte autoAuditType) {
		setField("autoAuditType", autoAuditType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.version
	 * 
	 * @return the value of cust.version
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.version
	 * 
	 * @param version
	 *            the value for cust.version
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setVersion(Integer version) {
		setField("version", version);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.business_no
	 * 
	 * @return the value of cust.business_no
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public Byte getBusinessNo() {
		return businessNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.business_no
	 * 
	 * @param businessNo
	 *            the value for cust.business_no
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setBusinessNo(Byte businessNo) {
		setField("businessNo", businessNo);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.business_details
	 * 
	 * @return the value of cust.business_details
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getBusinessDetails() {
		return businessDetails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.business_details
	 * 
	 * @param businessDetails
	 *            the value for cust.business_details
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setBusinessDetails(String businessDetails) {
		businessDetails = businessDetails == null ? null : businessDetails.trim();

		setField("businessDetails", businessDetails);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cust.stat_3
	 * 
	 * @return the value of cust.stat_3
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public String getStat3() {
		return stat3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cust.stat_3
	 * 
	 * @param stat3
	 *            the value for cust.stat_3
	 * 
	 * @mbggenerated Thu Aug 11 14:26:57 CST 2011
	 */
	public void setStat3(String stat3) {
		stat3 = stat3 == null ? null : stat3.trim();

		setField("stat3", stat3);
	}
}