CREATE DATABASE db1_master;
CREATE DATABASE db1_slave1;
CREATE DATABASE db1_slave2;

CREATE DATABASE db2_master;
CREATE DATABASE db2_slave1;
CREATE DATABASE db2_slave2;

CREATE DATABASE db3_master;
CREATE DATABASE db3_slave1;
CREATE DATABASE db3_slave2;

USE db1_master;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db1_slave1;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db1_slave2;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_master;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_slave1;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_slave2;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_master;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_slave1;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_slave2;
CREATE TABLE `user0` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `user1` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;