package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class AreaWordBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_area_word.c_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	@ColumnDescription(desc = "主键")
	@Id
	private Long cId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_area_word.c_word
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	@ColumnDescription(desc = "地域词")
	private String cWord;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_area_word.addedUser
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	@ColumnDescription(desc = "添加人")
	private Long addeduser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_area_word.addedTime
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	@ColumnDescription(desc = "添加时间")
	private Date addedtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_area_word.pos_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long posId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_area_word.c_id
	 * 
	 * @return the value of td_area_word.c_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public Long getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_area_word.c_id
	 * 
	 * @param cId
	 *            the value for td_area_word.c_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public void setcId(Long cId) {
		setField("cId", cId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_area_word.c_word
	 * 
	 * @return the value of td_area_word.c_word
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public String getcWord() {
		return cWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_area_word.c_word
	 * 
	 * @param cWord
	 *            the value for td_area_word.c_word
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public void setcWord(String cWord) {
		cWord = cWord == null ? null : cWord.trim();

		setField("cWord", cWord);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_area_word.addedUser
	 * 
	 * @return the value of td_area_word.addedUser
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public Long getAddeduser() {
		return addeduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_area_word.addedUser
	 * 
	 * @param addeduser
	 *            the value for td_area_word.addedUser
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public void setAddeduser(Long addeduser) {
		setField("addeduser", addeduser);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_area_word.addedTime
	 * 
	 * @return the value of td_area_word.addedTime
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public Date getAddedtime() {
		return addedtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_area_word.addedTime
	 * 
	 * @param addedtime
	 *            the value for td_area_word.addedTime
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public void setAddedtime(Date addedtime) {
		setField("addedtime", addedtime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_area_word.pos_id
	 * 
	 * @return the value of td_area_word.pos_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public Long getPosId() {
		return posId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_area_word.pos_id
	 * 
	 * @param posId
	 *            the value for td_area_word.pos_id
	 * 
	 * @mbggenerated Fri Jul 22 14:52:45 CST 2011
	 */
	public void setPosId(Long posId) {
		setField("posId", posId);
	}
}