package com.baidu.rigel.unique.bo;

import java.io.Serializable;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class BlacklistPhoneBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist_phone.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist_phone.blacklist_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "外键，表td_blacklist主键")
	private Long blacklistId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist_phone.phonenum
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "联系电话")
	private String phonenum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist_phone.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "0:not deleted 1:deleted")
	private Short delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist_phone.id
	 * 
	 * @return the value of td_blacklist_phone.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist_phone.id
	 * 
	 * @param id
	 *            the value for td_blacklist_phone.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist_phone.blacklist_id
	 * 
	 * @return the value of td_blacklist_phone.blacklist_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getBlacklistId() {
		return blacklistId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist_phone.blacklist_id
	 * 
	 * @param blacklistId
	 *            the value for td_blacklist_phone.blacklist_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setBlacklistId(Long blacklistId) {
		setField("blacklistId", blacklistId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist_phone.phonenum
	 * 
	 * @return the value of td_blacklist_phone.phonenum
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist_phone.phonenum
	 * 
	 * @param phonenum
	 *            the value for td_blacklist_phone.phonenum
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setPhonenum(String phonenum) {
		phonenum = phonenum == null ? null : phonenum.trim();

		setField("phonenum", phonenum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist_phone.del_flag
	 * 
	 * @return the value of td_blacklist_phone.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist_phone.del_flag
	 * 
	 * @param delFlag
	 *            the value for td_blacklist_phone.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setDelFlag(Short delFlag) {
		setField("delFlag", delFlag);
	}
}