package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class BlacklistBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.blacklist_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long blacklistId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.company_name
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String companyName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.company_phone
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String companyPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.creator_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long creatorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.create_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.update_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long updateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.update_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "0：正常 1：禁用")
	private Short delFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.url
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "鍏?徃url")
	private String url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_blacklist.src
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	@ColumnDescription(desc = "0:鍏?徃鎸囧畾,1:AD鐧藉悕鍗")
	private Short src;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.blacklist_id
	 * 
	 * @return the value of td_blacklist.blacklist_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Long getBlacklistId() {
		return blacklistId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.blacklist_id
	 * 
	 * @param blacklistId
	 *            the value for td_blacklist.blacklist_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setBlacklistId(Long blacklistId) {
		setField("blacklistId", blacklistId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.company_name
	 * 
	 * @return the value of td_blacklist.company_name
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.company_name
	 * 
	 * @param companyName
	 *            the value for td_blacklist.company_name
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setCompanyName(String companyName) {
		companyName = companyName == null ? null : companyName.trim();

		setField("companyName", companyName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.company_phone
	 * 
	 * @return the value of td_blacklist.company_phone
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public String getCompanyPhone() {
		return companyPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.company_phone
	 * 
	 * @param companyPhone
	 *            the value for td_blacklist.company_phone
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setCompanyPhone(String companyPhone) {
		companyPhone = companyPhone == null ? null : companyPhone.trim();

		setField("companyPhone", companyPhone);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.creator_id
	 * 
	 * @return the value of td_blacklist.creator_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Long getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.creator_id
	 * 
	 * @param creatorId
	 *            the value for td_blacklist.creator_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setCreatorId(Long creatorId) {
		setField("creatorId", creatorId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.create_time
	 * 
	 * @return the value of td_blacklist.create_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.create_time
	 * 
	 * @param createTime
	 *            the value for td_blacklist.create_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setCreateTime(Date createTime) {
		setField("createTime", createTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.update_id
	 * 
	 * @return the value of td_blacklist.update_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Long getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.update_id
	 * 
	 * @param updateId
	 *            the value for td_blacklist.update_id
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setUpdateId(Long updateId) {
		setField("updateId", updateId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.update_time
	 * 
	 * @return the value of td_blacklist.update_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.update_time
	 * 
	 * @param updateTime
	 *            the value for td_blacklist.update_time
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setUpdateTime(Date updateTime) {
		setField("updateTime", updateTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.del_flag
	 * 
	 * @return the value of td_blacklist.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.del_flag
	 * 
	 * @param delFlag
	 *            the value for td_blacklist.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setDelFlag(Short delFlag) {
		setField("delFlag", delFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.url
	 * 
	 * @return the value of td_blacklist.url
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.url
	 * 
	 * @param url
	 *            the value for td_blacklist.url
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setUrl(String url) {
		url = url == null ? null : url.trim();

		setField("url", url);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_blacklist.src
	 * 
	 * @return the value of td_blacklist.src
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public Short getSrc() {
		return src;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_blacklist.src
	 * 
	 * @param src
	 *            the value for td_blacklist.src
	 * 
	 * @mbggenerated Mon Jul 25 17:40:22 CST 2011
	 */
	public void setSrc(Short src) {
		setField("src", src);
	}
}