package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class NoncoreWordBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.word
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String word;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.creator_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long creatorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.create_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long updateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word.del_flag
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "0:not deleted 1:deleted")
	private Short delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.id
	 * 
	 * @return the value of td_noncore_word.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.id
	 * 
	 * @param id
	 *            the value for td_noncore_word.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.word
	 * 
	 * @return the value of td_noncore_word.word
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public String getWord() {
		return word;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.word
	 * 
	 * @param word
	 *            the value for td_noncore_word.word
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setWord(String word) {
		word = word == null ? null : word.trim();

		setField("word", word);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.creator_id
	 * 
	 * @return the value of td_noncore_word.creator_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.creator_id
	 * 
	 * @param creatorId
	 *            the value for td_noncore_word.creator_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setCreatorId(Long creatorId) {
		setField("creatorId", creatorId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.create_time
	 * 
	 * @return the value of td_noncore_word.create_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.create_time
	 * 
	 * @param createTime
	 *            the value for td_noncore_word.create_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setCreateTime(Date createTime) {
		setField("createTime", createTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.update_id
	 * 
	 * @return the value of td_noncore_word.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.update_id
	 * 
	 * @param updateId
	 *            the value for td_noncore_word.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setUpdateId(Long updateId) {
		setField("updateId", updateId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.update_time
	 * 
	 * @return the value of td_noncore_word.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.update_time
	 * 
	 * @param updateTime
	 *            the value for td_noncore_word.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setUpdateTime(Date updateTime) {
		setField("updateTime", updateTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word.del_flag
	 * 
	 * @return the value of td_noncore_word.del_flag
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word.del_flag
	 * 
	 * @param delFlag
	 *            the value for td_noncore_word.del_flag
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setDelFlag(Short delFlag) {
		setField("delFlag", delFlag);
	}
}