package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class NoncoreWordStrategyBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word_strategy.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word_strategy.enable_filter
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long enableFilter;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word_strategy.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long updateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_noncore_word_strategy.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word_strategy.id
	 * 
	 * @return the value of td_noncore_word_strategy.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word_strategy.id
	 * 
	 * @param id
	 *            the value for td_noncore_word_strategy.id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word_strategy.enable_filter
	 * 
	 * @return the value of td_noncore_word_strategy.enable_filter
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getEnableFilter() {
		return enableFilter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word_strategy.enable_filter
	 * 
	 * @param enableFilter
	 *            the value for td_noncore_word_strategy.enable_filter
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setEnableFilter(Long enableFilter) {
		setField("enableFilter", enableFilter);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word_strategy.update_id
	 * 
	 * @return the value of td_noncore_word_strategy.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Long getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word_strategy.update_id
	 * 
	 * @param updateId
	 *            the value for td_noncore_word_strategy.update_id
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setUpdateId(Long updateId) {
		setField("updateId", updateId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_noncore_word_strategy.update_time
	 * 
	 * @return the value of td_noncore_word_strategy.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_noncore_word_strategy.update_time
	 * 
	 * @param updateTime
	 *            the value for td_noncore_word_strategy.update_time
	 * 
	 * @mbggenerated Fri Aug 05 17:45:54 CST 2011
	 */
	public void setUpdateTime(Date updateTime) {
		setField("updateTime", updateTime);
	}
}