package com.baidu.rigel.unique.bo;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;
import java.io.Serializable;
import java.util.Date;

public abstract class PhoneBase extends FieldAccessVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.phone_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="主键ID")
    @Id
    private Integer phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.contact_or_recipId
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="关联的联系人或者收件人ID")
    private Integer contactOrRecipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.cust_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="客户ID")
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="收件人联系人类型 0:联系人,1:收件人")
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.ph_country_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="国家代码")
    private String phCountryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.ph_area_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="电话区号")
    private String phAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.ph_num
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="电话号码")
    private String phNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.ph_extension
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="分机号码")
    private String phExtension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.full_phone
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="")
    private String fullPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.ph_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="0：座机 1：手机")
    private Byte phType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.add_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="录入人ID")
    private Integer addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.add_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="录入时间")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.del_flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="删除标记 0:未删除,1:已删除")
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.disabled
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="是否失效：0：否，1：失效")
    private Byte disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.disabled_reason
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="失效原因")
    private String disabledReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.disabled_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="失效人")
    private Integer disabledUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.disabled_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="失效时间")
    private Date disabledTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone.int_put_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    @ColumnDescription(desc="来源：0：销售录入；1：批量导入；2：csc下发时;")
    private Byte intPutType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.phone_id
     *
     * @return the value of tb_phone.phone_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.phone_id
     *
     * @param phoneId the value for tb_phone.phone_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhoneId(Integer phoneId) {
        setField("phoneId", phoneId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.contact_or_recipId
     *
     * @return the value of tb_phone.contact_or_recipId
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Integer getContactOrRecipid() {
        return contactOrRecipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.contact_or_recipId
     *
     * @param contactOrRecipid the value for tb_phone.contact_or_recipId
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setContactOrRecipid(Integer contactOrRecipid) {
        setField("contactOrRecipid", contactOrRecipid);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.cust_id
     *
     * @return the value of tb_phone.cust_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.cust_id
     *
     * @param custId the value for tb_phone.cust_id
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setCustId(Integer custId) {
        setField("custId", custId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.flag
     *
     * @return the value of tb_phone.flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.flag
     *
     * @param flag the value for tb_phone.flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setFlag(Byte flag) {
        setField("flag", flag);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.ph_country_code
     *
     * @return the value of tb_phone.ph_country_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getPhCountryCode() {
        return phCountryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.ph_country_code
     *
     * @param phCountryCode the value for tb_phone.ph_country_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhCountryCode(String phCountryCode) {
        phCountryCode = phCountryCode == null ? null : phCountryCode.trim();

        setField("phCountryCode", phCountryCode);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.ph_area_code
     *
     * @return the value of tb_phone.ph_area_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getPhAreaCode() {
        return phAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.ph_area_code
     *
     * @param phAreaCode the value for tb_phone.ph_area_code
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhAreaCode(String phAreaCode) {
        phAreaCode = phAreaCode == null ? null : phAreaCode.trim();

        setField("phAreaCode", phAreaCode);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.ph_num
     *
     * @return the value of tb_phone.ph_num
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getPhNum() {
        return phNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.ph_num
     *
     * @param phNum the value for tb_phone.ph_num
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhNum(String phNum) {
        phNum = phNum == null ? null : phNum.trim();

        setField("phNum", phNum);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.ph_extension
     *
     * @return the value of tb_phone.ph_extension
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getPhExtension() {
        return phExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.ph_extension
     *
     * @param phExtension the value for tb_phone.ph_extension
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhExtension(String phExtension) {
        phExtension = phExtension == null ? null : phExtension.trim();

        setField("phExtension", phExtension);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.full_phone
     *
     * @return the value of tb_phone.full_phone
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getFullPhone() {
        return fullPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.full_phone
     *
     * @param fullPhone the value for tb_phone.full_phone
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setFullPhone(String fullPhone) {
        fullPhone = fullPhone == null ? null : fullPhone.trim();

        setField("fullPhone", fullPhone);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.ph_type
     *
     * @return the value of tb_phone.ph_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Byte getPhType() {
        return phType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.ph_type
     *
     * @param phType the value for tb_phone.ph_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setPhType(Byte phType) {
        setField("phType", phType);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.add_user
     *
     * @return the value of tb_phone.add_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Integer getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.add_user
     *
     * @param addUser the value for tb_phone.add_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setAddUser(Integer addUser) {
        setField("addUser", addUser);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.add_time
     *
     * @return the value of tb_phone.add_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.add_time
     *
     * @param addTime the value for tb_phone.add_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setAddTime(Date addTime) {
        setField("addTime", addTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.del_flag
     *
     * @return the value of tb_phone.del_flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.del_flag
     *
     * @param delFlag the value for tb_phone.del_flag
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setDelFlag(Byte delFlag) {
        setField("delFlag", delFlag);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.disabled
     *
     * @return the value of tb_phone.disabled
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.disabled
     *
     * @param disabled the value for tb_phone.disabled
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setDisabled(Byte disabled) {
        setField("disabled", disabled);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.disabled_reason
     *
     * @return the value of tb_phone.disabled_reason
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public String getDisabledReason() {
        return disabledReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.disabled_reason
     *
     * @param disabledReason the value for tb_phone.disabled_reason
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setDisabledReason(String disabledReason) {
        disabledReason = disabledReason == null ? null : disabledReason.trim();

        setField("disabledReason", disabledReason);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.disabled_user
     *
     * @return the value of tb_phone.disabled_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Integer getDisabledUser() {
        return disabledUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.disabled_user
     *
     * @param disabledUser the value for tb_phone.disabled_user
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setDisabledUser(Integer disabledUser) {
        setField("disabledUser", disabledUser);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.disabled_time
     *
     * @return the value of tb_phone.disabled_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Date getDisabledTime() {
        return disabledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.disabled_time
     *
     * @param disabledTime the value for tb_phone.disabled_time
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setDisabledTime(Date disabledTime) {
        setField("disabledTime", disabledTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phone.int_put_type
     *
     * @return the value of tb_phone.int_put_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public Byte getIntPutType() {
        return intPutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phone.int_put_type
     *
     * @param intPutType the value for tb_phone.int_put_type
     *
     * @mbggenerated Fri Jul 22 17:39:05 CST 2011
     */
    public void setIntPutType(Byte intPutType) {
        setField("intPutType", intPutType);
    }
}