package com.baidu.rigel.unique.bo;

import java.io.Serializable;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class SeasonCustListPhoneBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_season_cust_list_phone.id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_season_cust_list_phone.season_custlist_id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	@ColumnDescription(desc = "外键，该联系电话属于那个公司的")
	private Long seasonCustlistId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_season_cust_list_phone.phonenum
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	@ColumnDescription(desc = "联系电话")
	private String phonenum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_season_cust_list_phone.del_flag
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	@ColumnDescription(desc = "0:not deleted 1:deleted")
	private Short delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_season_cust_list_phone.id
	 * 
	 * @return the value of tb_season_cust_list_phone.id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_season_cust_list_phone.id
	 * 
	 * @param id
	 *            the value for tb_season_cust_list_phone.id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_season_cust_list_phone.season_custlist_id
	 * 
	 * @return the value of tb_season_cust_list_phone.season_custlist_id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public Long getSeasonCustlistId() {
		return seasonCustlistId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_season_cust_list_phone.season_custlist_id
	 * 
	 * @param seasonCustlistId
	 *            the value for tb_season_cust_list_phone.season_custlist_id
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public void setSeasonCustlistId(Long seasonCustlistId) {
		setField("seasonCustlistId", seasonCustlistId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_season_cust_list_phone.phonenum
	 * 
	 * @return the value of tb_season_cust_list_phone.phonenum
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_season_cust_list_phone.phonenum
	 * 
	 * @param phonenum
	 *            the value for tb_season_cust_list_phone.phonenum
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public void setPhonenum(String phonenum) {
		phonenum = phonenum == null ? null : phonenum.trim();

		setField("phonenum", phonenum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_season_cust_list_phone.del_flag
	 * 
	 * @return the value of tb_season_cust_list_phone.del_flag
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_season_cust_list_phone.del_flag
	 * 
	 * @param delFlag
	 *            the value for tb_season_cust_list_phone.del_flag
	 * 
	 * @mbggenerated Fri Jul 29 12:50:39 CST 2011
	 */
	public void setDelFlag(Short delFlag) {
		setField("delFlag", delFlag);
	}
}