package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class ShifenCustWhiteListBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.cust_name
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "客户公司名")
	private String custName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.url
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "客户url")
	private String url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.cust_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "客户id")
	private Long custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.user_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "指定销售id")
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.pos_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "指定销售所在部门id")
	private Long posId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.create_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "创建人")
	private Long createId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.create_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "创建时间")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.update_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "最后的更新人")
	private Long updateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.update_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "更新时间")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_shifen_cust_white_list.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	@ColumnDescription(desc = "0:not deleted 1:deleted")
	private Short delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.id
	 * 
	 * @return the value of tb_shifen_cust_white_list.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.id
	 * 
	 * @param id
	 *            the value for tb_shifen_cust_white_list.id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setId(Integer id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.cust_name
	 * 
	 * @return the value of tb_shifen_cust_white_list.cust_name
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.cust_name
	 * 
	 * @param custName
	 *            the value for tb_shifen_cust_white_list.cust_name
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setCustName(String custName) {
		custName = custName == null ? null : custName.trim();

		setField("custName", custName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.url
	 * 
	 * @return the value of tb_shifen_cust_white_list.url
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.url
	 * 
	 * @param url
	 *            the value for tb_shifen_cust_white_list.url
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setUrl(String url) {
		url = url == null ? null : url.trim();

		setField("url", url);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.cust_id
	 * 
	 * @return the value of tb_shifen_cust_white_list.cust_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.cust_id
	 * 
	 * @param custId
	 *            the value for tb_shifen_cust_white_list.cust_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setCustId(Long custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.user_id
	 * 
	 * @return the value of tb_shifen_cust_white_list.user_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.user_id
	 * 
	 * @param userId
	 *            the value for tb_shifen_cust_white_list.user_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setUserId(Long userId) {
		setField("userId", userId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.pos_id
	 * 
	 * @return the value of tb_shifen_cust_white_list.pos_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getPosId() {
		return posId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.pos_id
	 * 
	 * @param posId
	 *            the value for tb_shifen_cust_white_list.pos_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setPosId(Long posId) {
		setField("posId", posId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.create_id
	 * 
	 * @return the value of tb_shifen_cust_white_list.create_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.create_id
	 * 
	 * @param createId
	 *            the value for tb_shifen_cust_white_list.create_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setCreateId(Long createId) {
		setField("createId", createId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.create_time
	 * 
	 * @return the value of tb_shifen_cust_white_list.create_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.create_time
	 * 
	 * @param createTime
	 *            the value for tb_shifen_cust_white_list.create_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setCreateTime(Date createTime) {
		setField("createTime", createTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.update_id
	 * 
	 * @return the value of tb_shifen_cust_white_list.update_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Long getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.update_id
	 * 
	 * @param updateId
	 *            the value for tb_shifen_cust_white_list.update_id
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setUpdateId(Long updateId) {
		setField("updateId", updateId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.update_time
	 * 
	 * @return the value of tb_shifen_cust_white_list.update_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.update_time
	 * 
	 * @param updateTime
	 *            the value for tb_shifen_cust_white_list.update_time
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setUpdateTime(Date updateTime) {
		setField("updateTime", updateTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_shifen_cust_white_list.del_flag
	 * 
	 * @return the value of tb_shifen_cust_white_list.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_shifen_cust_white_list.del_flag
	 * 
	 * @param delFlag
	 *            the value for tb_shifen_cust_white_list.del_flag
	 * 
	 * @mbggenerated Wed Jul 27 18:34:30 CST 2011
	 */
	public void setDelFlag(Short delFlag) {
		setField("delFlag", delFlag);
	}
}