package com.baidu.rigel.unique.bo;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class UrlWhitelistBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	@Id
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.pos_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long posId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.url
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.domain
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String domain;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.creator_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long creatorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.create_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.update_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Long updateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.update_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.del_flag
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Byte delFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.c_type
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Short cType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.invalidate
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private Date invalidate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column td_url_whitelist.c_desc
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String cDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.id
	 * 
	 * @return the value of td_url_whitelist.id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.id
	 * 
	 * @param id
	 *            the value for td_url_whitelist.id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setId(Long id) {
		setField("id", id);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.pos_id
	 * 
	 * @return the value of td_url_whitelist.pos_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Long getPosId() {
		return posId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.pos_id
	 * 
	 * @param posId
	 *            the value for td_url_whitelist.pos_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setPosId(Long posId) {
		setField("posId", posId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.url
	 * 
	 * @return the value of td_url_whitelist.url
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.url
	 * 
	 * @param url
	 *            the value for td_url_whitelist.url
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setUrl(String url) {
		url = url == null ? null : url.trim();

		setField("url", url);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.domain
	 * 
	 * @return the value of td_url_whitelist.domain
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.domain
	 * 
	 * @param domain
	 *            the value for td_url_whitelist.domain
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setDomain(String domain) {
		domain = domain == null ? null : domain.trim();

		setField("domain", domain);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.creator_id
	 * 
	 * @return the value of td_url_whitelist.creator_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Long getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.creator_id
	 * 
	 * @param creatorId
	 *            the value for td_url_whitelist.creator_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setCreatorId(Long creatorId) {
		setField("creatorId", creatorId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.create_time
	 * 
	 * @return the value of td_url_whitelist.create_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.create_time
	 * 
	 * @param createTime
	 *            the value for td_url_whitelist.create_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setCreateTime(Date createTime) {
		setField("createTime", createTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.update_id
	 * 
	 * @return the value of td_url_whitelist.update_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Long getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.update_id
	 * 
	 * @param updateId
	 *            the value for td_url_whitelist.update_id
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setUpdateId(Long updateId) {
		setField("updateId", updateId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.update_time
	 * 
	 * @return the value of td_url_whitelist.update_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.update_time
	 * 
	 * @param updateTime
	 *            the value for td_url_whitelist.update_time
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setUpdateTime(Date updateTime) {
		setField("updateTime", updateTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.del_flag
	 * 
	 * @return the value of td_url_whitelist.del_flag
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.del_flag
	 * 
	 * @param delFlag
	 *            the value for td_url_whitelist.del_flag
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setDelFlag(Byte delFlag) {
		setField("delFlag", delFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.c_type
	 * 
	 * @return the value of td_url_whitelist.c_type
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Short getcType() {
		return cType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.c_type
	 * 
	 * @param cType
	 *            the value for td_url_whitelist.c_type
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setcType(Short cType) {
		setField("cType", cType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.invalidate
	 * 
	 * @return the value of td_url_whitelist.invalidate
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public Date getInvalidate() {
		return invalidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.invalidate
	 * 
	 * @param invalidate
	 *            the value for td_url_whitelist.invalidate
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setInvalidate(Date invalidate) {
		setField("invalidate", invalidate);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column td_url_whitelist.c_desc
	 * 
	 * @return the value of td_url_whitelist.c_desc
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public String getcDesc() {
		return cDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column td_url_whitelist.c_desc
	 * 
	 * @param cDesc
	 *            the value for td_url_whitelist.c_desc
	 * 
	 * @mbggenerated Thu Jul 28 18:39:20 CST 2011
	 */
	public void setcDesc(String cDesc) {
		cDesc = cDesc == null ? null : cDesc.trim();

		setField("cDesc", cDesc);
	}
}