package com.baidu.rigel.unique.bo.xuanyuan;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustContactBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Long contactId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "客户资料ID")
	private Integer custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_name
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人名称")
	private String contactName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.company_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人公司邮箱")
	private String companyMail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.personal_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人私人邮箱")
	private String personalMail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_duty
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人职务")
	private String contactDuty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_policy_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人决策类型")
	private Integer contactPolicyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_sex
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人性别 0：男，1：女，2：未知")
	private Byte contactSex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.contact_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人备注")
	private String contactRemark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人录入人ID")
	private Integer addUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "联系人录入时间")
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "删除标记 0:未删除,1:已删除")
	private Byte delFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.disabled
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "是否失效：0：否，1：失效")
	private Byte disabled;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.disabled_reason
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "失效原因")
	private String disabledReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.disabled_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "失效人")
	private Integer disabledUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.disabled_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "失效时间")
	private Date disabledTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_cust_contact.int_put_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	@ColumnDescription(desc = "来源：0：销售录入；1：批量导入；2：csc下发时;")
	private Byte intPutType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_id
	 * 
	 * @return the value of tb_cust_contact.contact_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Long getContactId() {
		return contactId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_id
	 * 
	 * @param contactId
	 *            the value for tb_cust_contact.contact_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactId(Long contactId) {
		setField("contactId", contactId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.cust_id
	 * 
	 * @return the value of tb_cust_contact.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.cust_id
	 * 
	 * @param custId
	 *            the value for tb_cust_contact.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setCustId(Integer custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_name
	 * 
	 * @return the value of tb_cust_contact.contact_name
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_name
	 * 
	 * @param contactName
	 *            the value for tb_cust_contact.contact_name
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactName(String contactName) {
		contactName = contactName == null ? null : contactName.trim();

		setField("contactName", contactName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.company_mail
	 * 
	 * @return the value of tb_cust_contact.company_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getCompanyMail() {
		return companyMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.company_mail
	 * 
	 * @param companyMail
	 *            the value for tb_cust_contact.company_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setCompanyMail(String companyMail) {
		companyMail = companyMail == null ? null : companyMail.trim();

		setField("companyMail", companyMail);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.personal_mail
	 * 
	 * @return the value of tb_cust_contact.personal_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getPersonalMail() {
		return personalMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.personal_mail
	 * 
	 * @param personalMail
	 *            the value for tb_cust_contact.personal_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setPersonalMail(String personalMail) {
		personalMail = personalMail == null ? null : personalMail.trim();

		setField("personalMail", personalMail);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_duty
	 * 
	 * @return the value of tb_cust_contact.contact_duty
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getContactDuty() {
		return contactDuty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_duty
	 * 
	 * @param contactDuty
	 *            the value for tb_cust_contact.contact_duty
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactDuty(String contactDuty) {
		contactDuty = contactDuty == null ? null : contactDuty.trim();

		setField("contactDuty", contactDuty);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_policy_type
	 * 
	 * @return the value of tb_cust_contact.contact_policy_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Integer getContactPolicyType() {
		return contactPolicyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_policy_type
	 * 
	 * @param contactPolicyType
	 *            the value for tb_cust_contact.contact_policy_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactPolicyType(Integer contactPolicyType) {
		setField("contactPolicyType", contactPolicyType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_sex
	 * 
	 * @return the value of tb_cust_contact.contact_sex
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Byte getContactSex() {
		return contactSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_sex
	 * 
	 * @param contactSex
	 *            the value for tb_cust_contact.contact_sex
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactSex(Byte contactSex) {
		setField("contactSex", contactSex);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.contact_remark
	 * 
	 * @return the value of tb_cust_contact.contact_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getContactRemark() {
		return contactRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.contact_remark
	 * 
	 * @param contactRemark
	 *            the value for tb_cust_contact.contact_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setContactRemark(String contactRemark) {
		contactRemark = contactRemark == null ? null : contactRemark.trim();

		setField("contactRemark", contactRemark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.add_user
	 * 
	 * @return the value of tb_cust_contact.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Integer getAddUser() {
		return addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.add_user
	 * 
	 * @param addUser
	 *            the value for tb_cust_contact.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setAddUser(Integer addUser) {
		setField("addUser", addUser);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.add_time
	 * 
	 * @return the value of tb_cust_contact.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.add_time
	 * 
	 * @param addTime
	 *            the value for tb_cust_contact.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setAddTime(Date addTime) {
		setField("addTime", addTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.del_flag
	 * 
	 * @return the value of tb_cust_contact.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.del_flag
	 * 
	 * @param delFlag
	 *            the value for tb_cust_contact.del_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setDelFlag(Byte delFlag) {
		setField("delFlag", delFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.disabled
	 * 
	 * @return the value of tb_cust_contact.disabled
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Byte getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.disabled
	 * 
	 * @param disabled
	 *            the value for tb_cust_contact.disabled
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setDisabled(Byte disabled) {
		setField("disabled", disabled);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.disabled_reason
	 * 
	 * @return the value of tb_cust_contact.disabled_reason
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public String getDisabledReason() {
		return disabledReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.disabled_reason
	 * 
	 * @param disabledReason
	 *            the value for tb_cust_contact.disabled_reason
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setDisabledReason(String disabledReason) {
		disabledReason = disabledReason == null ? null : disabledReason.trim();

		setField("disabledReason", disabledReason);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.disabled_user
	 * 
	 * @return the value of tb_cust_contact.disabled_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Integer getDisabledUser() {
		return disabledUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.disabled_user
	 * 
	 * @param disabledUser
	 *            the value for tb_cust_contact.disabled_user
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setDisabledUser(Integer disabledUser) {
		setField("disabledUser", disabledUser);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.disabled_time
	 * 
	 * @return the value of tb_cust_contact.disabled_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Date getDisabledTime() {
		return disabledTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.disabled_time
	 * 
	 * @param disabledTime
	 *            the value for tb_cust_contact.disabled_time
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setDisabledTime(Date disabledTime) {
		setField("disabledTime", disabledTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_cust_contact.int_put_type
	 * 
	 * @return the value of tb_cust_contact.int_put_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public Byte getIntPutType() {
		return intPutType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_cust_contact.int_put_type
	 * 
	 * @param intPutType
	 *            the value for tb_cust_contact.int_put_type
	 * 
	 * @mbggenerated Mon Jul 25 15:05:51 CST 2011
	 */
	public void setIntPutType(Byte intPutType) {
		setField("intPutType", intPutType);
	}
}