package com.baidu.rigel.unique.bo.xuanyuan;

import java.io.Serializable;
import java.util.Date;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;

public abstract class CustomerBase extends FieldAccessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "主键ID")
	@Id
	private Long custId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.orgnz_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "组织ID")
	private Integer orgnzId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.pose_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "岗位ID")
	private Long poseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户类型 0:普通企业 1:特殊企业 2:个人客户")
	private Short custType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户名称")
	private String custName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.personal_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "个人类型用户 客户备注,只有在个人类型时，才有可能不为null,其他类型时均为null")
	private String personalRemark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_full_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户全称")
	private String custFullName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_branch_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户分支机构名称")
	private String custBranchName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_addr
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户地址")
	private String custAddr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_zip_code
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户邮编")
	private String custZipCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户邮箱")
	private String custMail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_fax
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户传真,内容为格式为:区号-传真号-分机号")
	private String custFax;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_trade_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户一级行业对应的ID")
	private Integer custTrade1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_trade_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户二级行业对应的ID")
	private Integer custTrade2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_prov
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户所属省ID")
	private Integer custProv;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_city
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户所属市ID")
	private Integer custCity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_district
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户所属区ID")
	private Integer custDistrict;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_card_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户证件类型")
	private Integer custCardType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_card_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户证件编号")
	private String custCardNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_invoice_nm
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户发票抬头")
	private String custInvoiceNm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_scale
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户公司规模ID")
	private Integer custScale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_capital
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户注册资金ID")
	private Integer custCapital;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.have_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "是否有过网络推广历史 0:没有，1:有")
	private Byte haveNetIdea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户网络意识,多选")
	private Integer custNetIdea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_net_idea_other
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户网络意识其他内容")
	private String custNetIdeaOther;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_product
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户主营业务")
	private String custProduct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_priority
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "优先级 0:优先审核 1:入自有库 2:入公共库")
	private Byte custPriority;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户一级状态 0:新提交 1:确认中 2:待分配 3:跟进中 4:已提单 5:开户 6:放弃 7:废弃")
	private Byte custStat1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户二级状态 00:新提交 10:确认中 11:待审核 12:待清洗 13:待审核需清洗 14:已审核待清洗 ；20:已审核 21:已清洗 22:搁置期满；30:跟进初始状态0 ；40:已提单 41:订单审核 42:客户确认 ；60:客户置换 61:永久放弃 ；70:审核废弃 71:清洗废弃 72:管理废弃")
	private Byte custStat2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_his_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户历史一级状态 0:新提交 1:确认中 2:待分配 3:跟进中 4:已提单 5:开户 6:放弃 7:废弃")
	private Byte custHisStat1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_his_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户历史二级状态 00:新提交 10:确认中 11:待审核 12:待清洗 13:待审核需清洗 14:已审核待清洗 ；20:已审核 21:已清洗 22:搁置期满；30:跟进初始状态0 ；40:已提单 41:订单审核 42:客户确认 ；60:客户置换 61:永久放弃 ；70:审核废弃 71:清洗废弃 72:管理废弃")
	private Byte custHisStat2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.black_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "黑名单标记 0:黑名单 1:正常")
	private Byte blackFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料录入人ID")
	private Long addUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料提交时间")
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.upd_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料修改人ID")
	private Long updUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.upd_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料修改时间")
	private Date updTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_replace_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料被置换次数")
	private Integer custReplaceNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_quit_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料被放弃次数")
	private Integer custQuitNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_follow_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料被跟踪次数")
	private Integer custFollowNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_input_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "资料来源 ：0:销售录入 1:批量导入 2:网上注册 ")
	private Byte custInputType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_input_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户资料来源描述")
	private String custInputRemark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_have_web_site
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户建站情况 0:已有网站，1:没有网站，2:未知")
	private Byte custHaveWebSite;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_no_web_site_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户无网站说明类型")
	private Byte custNoWebSiteType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.use_computer
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "客户是否会使用电脑 0:会使用,1:不会使用")
	private Byte useComputer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.auto_audit_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "自动审核结果：0 通过;1 质疑;2 老户新开;3 一户多开")
	private Byte autoAuditType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.follow_audit
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "是否为跟进中待审核：0 不需要(默认值);1 需要等待审核")
	private Byte followAudit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.batch_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "批次号")
	private String batchNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.auto_assign
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "是否参与自动分配：0 参与(默认)，1 不参与")
	private Byte autoAssign;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.channel_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "渠道名称")
	private String channelName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.quit_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	@ColumnDescription(desc = "")
	private String quitUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_id
	 * 
	 * @return the value of tb_customer.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_id
	 * 
	 * @param custId
	 *            the value for tb_customer.cust_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustId(Long custId) {
		setField("custId", custId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.orgnz_id
	 * 
	 * @return the value of tb_customer.orgnz_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getOrgnzId() {
		return orgnzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.orgnz_id
	 * 
	 * @param orgnzId
	 *            the value for tb_customer.orgnz_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setOrgnzId(Integer orgnzId) {
		setField("orgnzId", orgnzId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.pose_id
	 * 
	 * @return the value of tb_customer.pose_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Long getPoseId() {
		return poseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.pose_id
	 * 
	 * @param poseId
	 *            the value for tb_customer.pose_id
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setPoseId(Long poseId) {
		setField("poseId", poseId);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_type
	 * 
	 * @return the value of tb_customer.cust_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Short getCustType() {
		return custType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_type
	 * 
	 * @param custType
	 *            the value for tb_customer.cust_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustType(Short custType) {
		setField("custType", custType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_name
	 * 
	 * @return the value of tb_customer.cust_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_name
	 * 
	 * @param custName
	 *            the value for tb_customer.cust_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustName(String custName) {
		custName = custName == null ? null : custName.trim();

		setField("custName", custName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.personal_remark
	 * 
	 * @return the value of tb_customer.personal_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getPersonalRemark() {
		return personalRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.personal_remark
	 * 
	 * @param personalRemark
	 *            the value for tb_customer.personal_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setPersonalRemark(String personalRemark) {
		personalRemark = personalRemark == null ? null : personalRemark.trim();

		setField("personalRemark", personalRemark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.remark
	 * 
	 * @return the value of tb_customer.remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.remark
	 * 
	 * @param remark
	 *            the value for tb_customer.remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setRemark(String remark) {
		remark = remark == null ? null : remark.trim();

		setField("remark", remark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_full_name
	 * 
	 * @return the value of tb_customer.cust_full_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustFullName() {
		return custFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_full_name
	 * 
	 * @param custFullName
	 *            the value for tb_customer.cust_full_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustFullName(String custFullName) {
		custFullName = custFullName == null ? null : custFullName.trim();

		setField("custFullName", custFullName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_branch_name
	 * 
	 * @return the value of tb_customer.cust_branch_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustBranchName() {
		return custBranchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_branch_name
	 * 
	 * @param custBranchName
	 *            the value for tb_customer.cust_branch_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustBranchName(String custBranchName) {
		custBranchName = custBranchName == null ? null : custBranchName.trim();

		setField("custBranchName", custBranchName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_addr
	 * 
	 * @return the value of tb_customer.cust_addr
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustAddr() {
		return custAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_addr
	 * 
	 * @param custAddr
	 *            the value for tb_customer.cust_addr
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustAddr(String custAddr) {
		custAddr = custAddr == null ? null : custAddr.trim();

		setField("custAddr", custAddr);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_zip_code
	 * 
	 * @return the value of tb_customer.cust_zip_code
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustZipCode() {
		return custZipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_zip_code
	 * 
	 * @param custZipCode
	 *            the value for tb_customer.cust_zip_code
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustZipCode(String custZipCode) {
		custZipCode = custZipCode == null ? null : custZipCode.trim();

		setField("custZipCode", custZipCode);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_mail
	 * 
	 * @return the value of tb_customer.cust_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustMail() {
		return custMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_mail
	 * 
	 * @param custMail
	 *            the value for tb_customer.cust_mail
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustMail(String custMail) {
		custMail = custMail == null ? null : custMail.trim();

		setField("custMail", custMail);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_fax
	 * 
	 * @return the value of tb_customer.cust_fax
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustFax() {
		return custFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_fax
	 * 
	 * @param custFax
	 *            the value for tb_customer.cust_fax
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustFax(String custFax) {
		custFax = custFax == null ? null : custFax.trim();

		setField("custFax", custFax);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_trade_1
	 * 
	 * @return the value of tb_customer.cust_trade_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustTrade1() {
		return custTrade1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_trade_1
	 * 
	 * @param custTrade1
	 *            the value for tb_customer.cust_trade_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustTrade1(Integer custTrade1) {
		setField("custTrade1", custTrade1);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_trade_2
	 * 
	 * @return the value of tb_customer.cust_trade_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustTrade2() {
		return custTrade2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_trade_2
	 * 
	 * @param custTrade2
	 *            the value for tb_customer.cust_trade_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustTrade2(Integer custTrade2) {
		setField("custTrade2", custTrade2);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_prov
	 * 
	 * @return the value of tb_customer.cust_prov
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustProv() {
		return custProv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_prov
	 * 
	 * @param custProv
	 *            the value for tb_customer.cust_prov
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustProv(Integer custProv) {
		setField("custProv", custProv);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_city
	 * 
	 * @return the value of tb_customer.cust_city
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustCity() {
		return custCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_city
	 * 
	 * @param custCity
	 *            the value for tb_customer.cust_city
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustCity(Integer custCity) {
		setField("custCity", custCity);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_district
	 * 
	 * @return the value of tb_customer.cust_district
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustDistrict() {
		return custDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_district
	 * 
	 * @param custDistrict
	 *            the value for tb_customer.cust_district
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustDistrict(Integer custDistrict) {
		setField("custDistrict", custDistrict);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_card_type
	 * 
	 * @return the value of tb_customer.cust_card_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustCardType() {
		return custCardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_card_type
	 * 
	 * @param custCardType
	 *            the value for tb_customer.cust_card_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustCardType(Integer custCardType) {
		setField("custCardType", custCardType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_card_no
	 * 
	 * @return the value of tb_customer.cust_card_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustCardNo() {
		return custCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_card_no
	 * 
	 * @param custCardNo
	 *            the value for tb_customer.cust_card_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustCardNo(String custCardNo) {
		custCardNo = custCardNo == null ? null : custCardNo.trim();

		setField("custCardNo", custCardNo);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_invoice_nm
	 * 
	 * @return the value of tb_customer.cust_invoice_nm
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustInvoiceNm() {
		return custInvoiceNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_invoice_nm
	 * 
	 * @param custInvoiceNm
	 *            the value for tb_customer.cust_invoice_nm
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustInvoiceNm(String custInvoiceNm) {
		custInvoiceNm = custInvoiceNm == null ? null : custInvoiceNm.trim();

		setField("custInvoiceNm", custInvoiceNm);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_scale
	 * 
	 * @return the value of tb_customer.cust_scale
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustScale() {
		return custScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_scale
	 * 
	 * @param custScale
	 *            the value for tb_customer.cust_scale
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustScale(Integer custScale) {
		setField("custScale", custScale);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_capital
	 * 
	 * @return the value of tb_customer.cust_capital
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustCapital() {
		return custCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_capital
	 * 
	 * @param custCapital
	 *            the value for tb_customer.cust_capital
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustCapital(Integer custCapital) {
		setField("custCapital", custCapital);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.have_net_idea
	 * 
	 * @return the value of tb_customer.have_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getHaveNetIdea() {
		return haveNetIdea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.have_net_idea
	 * 
	 * @param haveNetIdea
	 *            the value for tb_customer.have_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setHaveNetIdea(Byte haveNetIdea) {
		setField("haveNetIdea", haveNetIdea);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_net_idea
	 * 
	 * @return the value of tb_customer.cust_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustNetIdea() {
		return custNetIdea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_net_idea
	 * 
	 * @param custNetIdea
	 *            the value for tb_customer.cust_net_idea
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustNetIdea(Integer custNetIdea) {
		setField("custNetIdea", custNetIdea);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_net_idea_other
	 * 
	 * @return the value of tb_customer.cust_net_idea_other
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustNetIdeaOther() {
		return custNetIdeaOther;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_net_idea_other
	 * 
	 * @param custNetIdeaOther
	 *            the value for tb_customer.cust_net_idea_other
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustNetIdeaOther(String custNetIdeaOther) {
		custNetIdeaOther = custNetIdeaOther == null ? null : custNetIdeaOther.trim();

		setField("custNetIdeaOther", custNetIdeaOther);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_product
	 * 
	 * @return the value of tb_customer.cust_product
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustProduct() {
		return custProduct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_product
	 * 
	 * @param custProduct
	 *            the value for tb_customer.cust_product
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustProduct(String custProduct) {
		custProduct = custProduct == null ? null : custProduct.trim();

		setField("custProduct", custProduct);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_priority
	 * 
	 * @return the value of tb_customer.cust_priority
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustPriority() {
		return custPriority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_priority
	 * 
	 * @param custPriority
	 *            the value for tb_customer.cust_priority
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustPriority(Byte custPriority) {
		setField("custPriority", custPriority);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_stat_1
	 * 
	 * @return the value of tb_customer.cust_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustStat1() {
		return custStat1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_stat_1
	 * 
	 * @param custStat1
	 *            the value for tb_customer.cust_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustStat1(Byte custStat1) {
		setField("custStat1", custStat1);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_stat_2
	 * 
	 * @return the value of tb_customer.cust_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustStat2() {
		return custStat2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_stat_2
	 * 
	 * @param custStat2
	 *            the value for tb_customer.cust_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustStat2(Byte custStat2) {
		setField("custStat2", custStat2);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_his_stat_1
	 * 
	 * @return the value of tb_customer.cust_his_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustHisStat1() {
		return custHisStat1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_his_stat_1
	 * 
	 * @param custHisStat1
	 *            the value for tb_customer.cust_his_stat_1
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustHisStat1(Byte custHisStat1) {
		setField("custHisStat1", custHisStat1);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_his_stat_2
	 * 
	 * @return the value of tb_customer.cust_his_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustHisStat2() {
		return custHisStat2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_his_stat_2
	 * 
	 * @param custHisStat2
	 *            the value for tb_customer.cust_his_stat_2
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustHisStat2(Byte custHisStat2) {
		setField("custHisStat2", custHisStat2);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.black_flag
	 * 
	 * @return the value of tb_customer.black_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getBlackFlag() {
		return blackFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.black_flag
	 * 
	 * @param blackFlag
	 *            the value for tb_customer.black_flag
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setBlackFlag(Byte blackFlag) {
		setField("blackFlag", blackFlag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.add_user
	 * 
	 * @return the value of tb_customer.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Long getAddUser() {
		return addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.add_user
	 * 
	 * @param addUser
	 *            the value for tb_customer.add_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setAddUser(Long addUser) {
		setField("addUser", addUser);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.add_time
	 * 
	 * @return the value of tb_customer.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.add_time
	 * 
	 * @param addTime
	 *            the value for tb_customer.add_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setAddTime(Date addTime) {
		setField("addTime", addTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.upd_user
	 * 
	 * @return the value of tb_customer.upd_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Long getUpdUser() {
		return updUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.upd_user
	 * 
	 * @param updUser
	 *            the value for tb_customer.upd_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setUpdUser(Long updUser) {
		setField("updUser", updUser);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.upd_time
	 * 
	 * @return the value of tb_customer.upd_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Date getUpdTime() {
		return updTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.upd_time
	 * 
	 * @param updTime
	 *            the value for tb_customer.upd_time
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setUpdTime(Date updTime) {
		setField("updTime", updTime);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_replace_num
	 * 
	 * @return the value of tb_customer.cust_replace_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustReplaceNum() {
		return custReplaceNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_replace_num
	 * 
	 * @param custReplaceNum
	 *            the value for tb_customer.cust_replace_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustReplaceNum(Integer custReplaceNum) {
		setField("custReplaceNum", custReplaceNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_quit_num
	 * 
	 * @return the value of tb_customer.cust_quit_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustQuitNum() {
		return custQuitNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_quit_num
	 * 
	 * @param custQuitNum
	 *            the value for tb_customer.cust_quit_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustQuitNum(Integer custQuitNum) {
		setField("custQuitNum", custQuitNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_follow_num
	 * 
	 * @return the value of tb_customer.cust_follow_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Integer getCustFollowNum() {
		return custFollowNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_follow_num
	 * 
	 * @param custFollowNum
	 *            the value for tb_customer.cust_follow_num
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustFollowNum(Integer custFollowNum) {
		setField("custFollowNum", custFollowNum);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_input_type
	 * 
	 * @return the value of tb_customer.cust_input_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustInputType() {
		return custInputType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_input_type
	 * 
	 * @param custInputType
	 *            the value for tb_customer.cust_input_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustInputType(Byte custInputType) {
		setField("custInputType", custInputType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_input_remark
	 * 
	 * @return the value of tb_customer.cust_input_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getCustInputRemark() {
		return custInputRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_input_remark
	 * 
	 * @param custInputRemark
	 *            the value for tb_customer.cust_input_remark
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustInputRemark(String custInputRemark) {
		custInputRemark = custInputRemark == null ? null : custInputRemark.trim();

		setField("custInputRemark", custInputRemark);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_have_web_site
	 * 
	 * @return the value of tb_customer.cust_have_web_site
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustHaveWebSite() {
		return custHaveWebSite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_have_web_site
	 * 
	 * @param custHaveWebSite
	 *            the value for tb_customer.cust_have_web_site
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustHaveWebSite(Byte custHaveWebSite) {
		setField("custHaveWebSite", custHaveWebSite);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_no_web_site_type
	 * 
	 * @return the value of tb_customer.cust_no_web_site_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getCustNoWebSiteType() {
		return custNoWebSiteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_no_web_site_type
	 * 
	 * @param custNoWebSiteType
	 *            the value for tb_customer.cust_no_web_site_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setCustNoWebSiteType(Byte custNoWebSiteType) {
		setField("custNoWebSiteType", custNoWebSiteType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.use_computer
	 * 
	 * @return the value of tb_customer.use_computer
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getUseComputer() {
		return useComputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.use_computer
	 * 
	 * @param useComputer
	 *            the value for tb_customer.use_computer
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setUseComputer(Byte useComputer) {
		setField("useComputer", useComputer);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.auto_audit_type
	 * 
	 * @return the value of tb_customer.auto_audit_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getAutoAuditType() {
		return autoAuditType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.auto_audit_type
	 * 
	 * @param autoAuditType
	 *            the value for tb_customer.auto_audit_type
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setAutoAuditType(Byte autoAuditType) {
		setField("autoAuditType", autoAuditType);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.follow_audit
	 * 
	 * @return the value of tb_customer.follow_audit
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getFollowAudit() {
		return followAudit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.follow_audit
	 * 
	 * @param followAudit
	 *            the value for tb_customer.follow_audit
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setFollowAudit(Byte followAudit) {
		setField("followAudit", followAudit);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.batch_no
	 * 
	 * @return the value of tb_customer.batch_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getBatchNo() {
		return batchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.batch_no
	 * 
	 * @param batchNo
	 *            the value for tb_customer.batch_no
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setBatchNo(String batchNo) {
		batchNo = batchNo == null ? null : batchNo.trim();

		setField("batchNo", batchNo);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.auto_assign
	 * 
	 * @return the value of tb_customer.auto_assign
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public Byte getAutoAssign() {
		return autoAssign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.auto_assign
	 * 
	 * @param autoAssign
	 *            the value for tb_customer.auto_assign
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setAutoAssign(Byte autoAssign) {
		setField("autoAssign", autoAssign);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.channel_name
	 * 
	 * @return the value of tb_customer.channel_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.channel_name
	 * 
	 * @param channelName
	 *            the value for tb_customer.channel_name
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setChannelName(String channelName) {
		channelName = channelName == null ? null : channelName.trim();

		setField("channelName", channelName);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.quit_user
	 * 
	 * @return the value of tb_customer.quit_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public String getQuitUser() {
		return quitUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.quit_user
	 * 
	 * @param quitUser
	 *            the value for tb_customer.quit_user
	 * 
	 * @mbggenerated Mon Jul 25 15:33:38 CST 2011
	 */
	public void setQuitUser(String quitUser) {
		quitUser = quitUser == null ? null : quitUser.trim();

		setField("quitUser", quitUser);
	}
}