package com.baidu.rigel.unique.bo.xuanyuan;

import com.baidu.rigel.platform.bo.FieldAccessVo;
import com.baidu.rigel.platform.bo.annotaions.ColumnDescription;
import com.baidu.rigel.platform.bo.annotaions.Id;
import java.io.Serializable;
import java.util.Date;

public abstract class FollowAssignBase extends FieldAccessVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.follow_assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="")
    @Id
    private Integer followAssignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.cust_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="")
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.follow_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="0表示分配到池")
    private Integer followId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.assign_type
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="0：手动分配 1：自动分配")
    private Byte assignType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.assign_rule_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="")
    private Integer assignRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="")
    private Integer assignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.assign_time
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="")
    private Date assignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_follow_assign.opt_postil
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    @ColumnDescription(desc="批注")
    private String optPostil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.follow_assign_id
     *
     * @return the value of tb_follow_assign.follow_assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Integer getFollowAssignId() {
        return followAssignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.follow_assign_id
     *
     * @param followAssignId the value for tb_follow_assign.follow_assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setFollowAssignId(Integer followAssignId) {
        setField("followAssignId", followAssignId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.cust_id
     *
     * @return the value of tb_follow_assign.cust_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.cust_id
     *
     * @param custId the value for tb_follow_assign.cust_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setCustId(Integer custId) {
        setField("custId", custId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.follow_id
     *
     * @return the value of tb_follow_assign.follow_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Integer getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.follow_id
     *
     * @param followId the value for tb_follow_assign.follow_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setFollowId(Integer followId) {
        setField("followId", followId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.assign_type
     *
     * @return the value of tb_follow_assign.assign_type
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Byte getAssignType() {
        return assignType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.assign_type
     *
     * @param assignType the value for tb_follow_assign.assign_type
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setAssignType(Byte assignType) {
        setField("assignType", assignType);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.assign_rule_id
     *
     * @return the value of tb_follow_assign.assign_rule_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Integer getAssignRuleId() {
        return assignRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.assign_rule_id
     *
     * @param assignRuleId the value for tb_follow_assign.assign_rule_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setAssignRuleId(Integer assignRuleId) {
        setField("assignRuleId", assignRuleId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.assign_id
     *
     * @return the value of tb_follow_assign.assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Integer getAssignId() {
        return assignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.assign_id
     *
     * @param assignId the value for tb_follow_assign.assign_id
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setAssignId(Integer assignId) {
        setField("assignId", assignId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.assign_time
     *
     * @return the value of tb_follow_assign.assign_time
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.assign_time
     *
     * @param assignTime the value for tb_follow_assign.assign_time
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setAssignTime(Date assignTime) {
        setField("assignTime", assignTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_follow_assign.opt_postil
     *
     * @return the value of tb_follow_assign.opt_postil
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public String getOptPostil() {
        return optPostil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_follow_assign.opt_postil
     *
     * @param optPostil the value for tb_follow_assign.opt_postil
     *
     * @mbggenerated Tue Jul 26 17:39:20 CST 2011
     */
    public void setOptPostil(String optPostil) {
        optPostil = optPostil == null ? null : optPostil.trim();

        setField("optPostil", optPostil);
    }
}